django_strat/strat/homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.Index.as_view(), name='home')
]

django_strat/strat/league/urls.py
from django.urls import path

from .views import players, teams, league

app_name = 'league'
urlpatterns = [
    path('players/', players.IndexView.as_view(), name='player_index'),
    path('players/<str:player_id>/', players.PlayerDetail.as_view(), name='player_detail'),
    # path('players/<str:player_id>/contract', views.contract, name='player_contract'),
    path('teams/', teams.TeamIndex.as_view(), name='team_index'),
    path('teams/<int:year>', teams.TeamIndex.as_view(), name='team_index'),
    path('teams/<int:year>/<str:abbreviation>/', teams.TeamRoster.as_view(), name='team_roster'),
    path('teams/<int:year>/<str:abbreviation>/stats/', teams.TeamRoster.as_view(), name='team_stats'),
    path('teams/<int:year>/<str:abbreviation>/roster/', teams.TeamRoster.as_view(), name='team_roster'),
    path('teams/<int:year>/<str:abbreviation>/contracts/', teams.TeamContracts.as_view(), name='team_contracts'),
    path('teams/<int:year>/<str:abbreviation>/arbitration/', teams.TeamArbitration.as_view(),
         name='team_arbitration'),
    path('teams/<int:year>/<str:abbreviation>/draft_picks/',
         teams.TeamDraftPick.as_view(), name='team_draft_picks'),
    path('draft', league.LeagueDraft.as_view(), name='draft'),
    path('draft/<int:year>/picks_index', league.LeagueDraftPicks.as_view(), name='draft_picks_index'),
    path('draft/<int:year>/players_index', league.LeagueDraftPlayers.as_view(), name='draft_players_index'),
    path('trades', league.LeagueTradesIndex.as_view(), name='trades_index'),
    path('trades/<int:id>', league.TradeDetail.as_view(), name='trade_detail'),
    path('free_agents', league.LeagueFreeAgentIndex.as_view(), name='free_agent_index'),
    ]

django_strat/strat/strat/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('league/', include('league.urls')),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('admin/', admin.site.urls),
]

django_strat/strat/homepage/models.py
from django.db import models

# Create your models here.

django_strat/strat/homepage/views.py
from django.shortcuts import render
from django.views import View


class Index(View):

    user = False

    def get(self, request):
        user = None
        if request.user.is_authenticated:
            user = request.user
        context = {
            'user': user,
        }
        return render(request, 'homepage/homepage.html', context)

django_strat/strat/homepage/templates/homepage/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css"
          href="{% static 'base.css' %}" />
    {% block page_title %}
        <title>BAD League</title>
    {% endblock page_title %}
</head>
<body>
    {% block header %}
        <header>
            <img src="{% static 'BAD_logo.jpg'%}"
                 alt="BAD League Logo"/>
            <h1>Building A Dynasty Strat-O-Matic League</h1>
        </header>
    {% endblock header %}
    {% block login %}
        {% if user %}
            <h4>Welcome {{user.first_name}} <a href="{% url 'logout' %}">Logout</a></h4>
        {% else %}
            <h4><a href="{% url 'login' %}">Log In</a></h4>
        {% endif %}
    {% endblock login %}
    {% block site_navigation %}
        <nav>
            <h2>
                <a href="{% url 'homepage:home' %}">Home</a> |
                News |
                Schedule |
                Standings |
                Statistics |
                <a href="{% url 'league:team_index' %}">Teams</a> |
                <a href="{% url 'league:player_index' %}">Players</a> |
                <a href="{% url 'league:trades_index' %}">Transactions</a> |
                <a href="{% url 'league:draft' %}">Draft</a> |
                <a href="{% url 'league:free_agent_index' %}">Free Agency</a>
            </h2>
        </nav>
    {% endblock site_navigation %}
    {% block part_header %}
    {% endblock part_header %}
    {% block part_navigation %}
    {% endblock part_navigation %}
    {% block content %}
        <p>No content displayed here, please contact the site admin if you believe this is an error.</p>
    {% endblock content %}
</body>
</html>

django_strat/strat/homepage/templates/homepage/homepage.html
{% extends "./base.html" %}
{% block page_title %}
    <title>BAD League Homepage</title>
{% endblock page_title %}

{% block content %}
    <article>
        <h1>Homepage</h1>
        <h2>Test to see where changes are committed.</h2>
    </article>
{% endblock %}