django_strat/strat/league/urls.py
from django.urls import path

from .views import players, teams, league

app_name = 'league'
urlpatterns = [
    path('players/', players.IndexView.as_view(), name='player_index'),
    path('players/<str:player_id>/', players.PlayerDetail.as_view(), name='player_detail'),
    # path('players/<str:player_id>/contract', views.contract, name='player_contract'),
    path('teams/', teams.TeamIndex.as_view(), name='team_index'),
    path('teams/<int:year>', teams.TeamIndex.as_view(), name='team_index'),
    path('teams/<int:year>/<str:abbreviation>/', teams.TeamRoster.as_view(), name='team_roster'),
    path('teams/<int:year>/<str:abbreviation>/stats/', teams.TeamRoster.as_view(), name='team_stats'),
    path('teams/<int:year>/<str:abbreviation>/roster/', teams.TeamRoster.as_view(), name='team_roster'),
    path('teams/<int:year>/<str:abbreviation>/contracts/', teams.TeamContracts.as_view(), name='team_contracts'),
    path('teams/<int:year>/<str:abbreviation>/arbitration/', teams.TeamArbitration.as_view(),
         name='team_arbitration'),
    path('teams/<int:year>/<str:abbreviation>/draft_picks/',
         teams.TeamDraftPick.as_view(), name='team_draft_picks'),
    path('draft', league.LeagueDraft.as_view(), name='draft'),
    path('draft/<int:year>/picks_index', league.LeagueDraftPicks.as_view(), name='draft_picks_index'),
    path('draft/<int:year>/players_index', league.LeagueDraftPlayers.as_view(), name='draft_players_index'),
    path('trades', league.LeagueTradesIndex.as_view(), name='trades_index'),
    path('trades/<int:id>', league.TradeDetail.as_view(), name='trade_detail'),
    path('free_agents', league.LeagueFreeAgentIndex.as_view(), name='free_agent_index'),
    ]

django_strat/strat/strat/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('league/', include('league.urls')),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('admin/', admin.site.urls),
]

django_strat/strat/league/views/home.py
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'league/home_page.html'

    def get_queryset(self):
        """
        Gives an empty queryset to allow loading of the home page.
        """
        return None

django_strat/strat/league/views/league.py
from django.shortcuts import render, get_list_or_404
from django.utils import timezone
from django.views import View

from league.models.teams import Team
from league.models.transactions import DraftPick, AvailableFreeAgent, AvailableDraftPick
from .league_helper import collect_trades, collect_trade


class LeagueDraft(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year
        context = {
            'year': year,
        }
        return render(request, 'league/league/draft.html', context)


class LeagueDraftPicks(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        teams = get_list_or_404(Team.objects.filter(year=year))
        picks = get_list_or_404(DraftPick.objects.filter(year=year)
                                      .order_by('round', 'order'))
        draft_picks = []
        for p in picks:
            number = ((p.round - 1) * 16) + p.order
            dft_pick = {
                'pick': p,
                'number': number,
            }
            draft_picks.append(dft_pick)
        context = {
            'teams': teams,
            'draft_picks': draft_picks
        }
        return render(request, 'league/league/draft_picks.html', context)


class LeagueDraftPlayers(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        draft_players = AvailableDraftPick.objects.filter(year=year)

        context = {
            'year': year,
            'draft_players': draft_players,
        }
        return render(request, 'league/league/draft_players.html', context)


class LeagueTradesIndex(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        trades = collect_trades(year)
        context = {
            'trades': trades,
            'year': year,
        }
        return render(request, 'league/league/trade_index.html', context)


class TradeDetail(View):

    def get(self, request, id):
        trade = collect_trade(id)
        context = {
            'trade': trade
        }
        return render(request, 'league/league/trade_detail.html', context)

class LeagueFreeAgentIndex(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        free_agents = AvailableFreeAgent.objects.filter(year=year)
        context = {
            'free_agents': free_agents,
            'year': year,
        }
        return render(request, 'league/league/free_agents.html', context)

django_strat/strat/league/views/league_helper.py
from league.models.transactions import Trades, TradePart,\
    TradePlayer, TradePick, TradeMoney


def collect_trades(year, team=None):
    if team is None:
        trade = Trades.objects.filter(year=year).order_by('date')
    else:
        trade = Trades.objects.filter(year=year, team=team).order_by('date')
    trades = []
    for t in trade:
        trd = collect_trade(t.id)
        trades.append(trd)
    return trades


def collect_trade(id):
    trade = Trades.objects.filter(id=id)
    trade_part = TradePart.objects.filter(trade=id)
    trade_vector_part = collect_trade_vectors(trade_part)
    trade_vector = []
    for t in trade_vector_part:
        trade_vector.append(collect_vector_part(t['giving'], t['receiving'], id))
    trade = {
        'trade': trade,
        'trade_vector': trade_vector,
    }
    return trade


def collect_trade_vectors(trade_parts):
    all_trade_vectors = []
    unique_trade_vectors = []
    for t in trade_parts:
        v = {
            'giving': t.team_giving,
            'receiving': t.team_receiving,
        }
        all_trade_vectors.append(v)
    for v in all_trade_vectors:
        if v not in unique_trade_vectors:
            unique_trade_vectors.append(v)
    return unique_trade_vectors


def collect_vector_part(giving, receiving, id):
    players = TradePlayer.objects.filter(team_giving=giving, team_receiving=receiving, trade=id)
    picks = TradePick.objects.filter(team_giving=giving, team_receiving=receiving, trade=id)
    money = TradeMoney.objects.filter(team_giving=giving, team_receiving=receiving, trade=id)
    vector = {
        'giving': giving,
        'receiving': receiving,
        'players': players,
        'picks': picks,
        'money': money,
    }
    return vector

django_strat/strat/league/views/player_helper.py
from league.models.transactions import AvailableFreeAgent, AvailableDraftPick
from league.models.players import HitterCardStats, \
    Contract
from league.models.players import HitterCardStats, \
    Contract
from league.models.transactions import AvailableFreeAgent, AvailableDraftPick


def collect_team(player, year):
    team = ''
    contract = Contract.objects.filter(player=player, year=year)
    if len(contract) == 1:
        team = '{} {}'.format(contract[0].team.location, contract[0].team.nickname)
    elif len(contract) == 0:
        free_agents = AvailableFreeAgent.objects.filter(player=player, year=year)
        if len(free_agents) == 1:
            team = 'Free Agent'
        else:
            draft_picks = AvailableDraftPick.objects.filter(player=player, year=year)
            if len(draft_picks) == 1:
                team = 'Available in Draft'
    return team


def collect_player_position(player):
    position = ''
    if player.player_type == 'p':
        position += 'Pitcher, '
    if player.player_type == 'x':
        position += 'Pitcher, '
    if player.player_type in 'hx':
        cards = HitterCardStats.objects.filter(player=player)
        defensive_strings = ''
        for c in cards:
            defensive_strings += '{} '.format(c.defensive_string)
        while len(defensive_strings) > 3:
            if defensive_strings[:2] == 'c-':
                if 'Catcher' not in position:
                    position += 'Catcher, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == '1b-':
                if 'Firstbase' not in position:
                    position += 'Firstbase, '
                defensive_strings = defensive_strings[3:]
            elif defensive_strings[:3] == '2b-':
                if 'Secondbase' not in position:
                    position += 'Secondbase, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == '3b-':
                if 'Thirdbase' not in position:
                    position += 'Thirdbase, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'ss-':
                if 'Shortstop' not in position:
                    position += 'Shortstop, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'lf-':
                if 'Left Field' not in position:
                    position += 'Left Field, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'cf-':
                if 'Center Field' not in position:
                    position += 'Center Field, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'rf-':
                if 'Right Field' not in position:
                    position += 'Right Field, '
            else:
                defensive_strings = defensive_strings[1:]
    position = position[:-2]
    return position

django_strat/strat/league/views/players.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views import generic, View

from league.models.players import Player, HitterCardStats, PitcherCardStats
from .player_helper import collect_player_position, collect_team


class IndexView(generic.ListView):
    template_name = 'league/player/index.html'
    context_object_name = 'player_list'

    def get_queryset(self):
        return Player.objects.filter(active=True)


class PlayerDetail(View):

    def get(self, request, player_id):
        player = get_object_or_404(Player, pk=player_id)
        hitting_card_stats = HitterCardStats.objects.filter(player=player_id).order_by('year')
        pitching_card_stats = PitcherCardStats.objects.filter(player=player_id).order_by('year')
        positions = collect_player_position(player)
        year = timezone.now().year
        teams = collect_team(player, year)
        context = {
            'player': player,
            'bats': player.batting_hand(),
            'throws': player.throwing_hand(),
            'positions': positions,
            'teams': teams,
            'hitting_card_stats': hitting_card_stats,
            'pitching_card_stats': pitching_card_stats,
        }
        return render(request, 'league/player/detail.html', context)

django_strat/strat/league/views/teams.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.utils import timezone
from django.views import View
from django_tables2 import RequestConfig

from league.forms.teams import RenewableList
from league.models.teams import Team
from league.tables.card_stats import TeamHitter, TeamPitcher
from league.views.team_helper import collect_teams, collect_team, collect_roster, \
    collect_payroll, collect_card_stats, collect_contract_display, collect_adjustments, \
    collect_renewable, collect_guarenteed, collect_arbitration, collect_draft_pick


class TeamIndex(View):
    """
    Gets a list of the teams for a given year
    """
    http_method_names = ['get']

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year
        years = set(Team.objects.all().values_list("year", flat=True))
        next_year, last_year = None, None
        if year + 1 in years:
            next_year = year + 1
        if year - 1 in years:
            last_year = year - 1
        team_list = collect_teams(year)
        for t in team_list:
            t = collect_roster(t)
            t = collect_payroll(t)

        context = {
            'team_list': team_list,
            'year': year,
            'last_year': last_year,
            'next_year': next_year,
        }
        return render(request, 'league/team/index.html', context)


class TeamStats(View):
    http_method_names = ['get']

    def get(self, request, abbreviation, year=None):
        if year is None:
            year = timezone.now().year

        team = collect_team(year, abbreviation)
        context = {
            'team': team,
        }
        return render(request, 'league/team/stats.html', context)


class TeamContracts(View):
    http_method_names = ['get']

    def get(self, request, year, abbreviation):
        team = collect_team(year=year, abbreviation=abbreviation)
        team = collect_roster(team)
        team = collect_payroll(team)
        team = collect_adjustments(team)
        for r in team['roster']:
            r['contract'] = collect_contract_display(r['contract'])
        context = {
            'team': team,
            'contract_list': ['Y1', 'Y2', 'Y3', 'Arb4', 'Arb5', 'Arb6', 'FA'],
        }
        return render(request, 'league/team/contracts.html', context)


class TeamOffSeasonContracts(UserPassesTestMixin, View):

    def test_func(self):
        """
        Test If the current user owns the current team.

        Returns:
            bool
        """
        my_path = self.request.path.split('/')
        year = my_path[1]
        abbreviation = my_path[2]
        if self.request.method.lower() == 'get':
            return True
        try:
            Team.objects.get(owner=self.request.user, year=year, abbreviation=abbreviation)
        except Team.DoesNotExist:
            return False
        return True

    def get(self, request, year, abbreviation):
        header = collect_team_header(abbreviation, year)
        contracts = collect_off_season_contracts(abbreviation, year)
        payroll = collect_payroll_elements(abbreviation, year)
        is_owner = Team.objects.filter(owner=self.request.user, year=year, abbreviation=abbreviation).count()
        context = {
            'is_owner': is_owner,
            'contracts': contracts,
            'payroll': payroll,
            'header': header,
        }
        return render(request, 'league/team/off_season_contracts.html', context)

    def post(self):
        pass


class TeamDraftPick(View):
    http_method_names = ['get']

    def get(self, request, year, abbreviation):
        team = collect_team(year=year, abbreviation=abbreviation)
        team = collect_draft_pick(team)
        context = {
            'team': team,
        }
        return render(request, 'league/team/draft_picks.html', context)


class TeamRoster(View):
    """
    Gets a roster for a specific team, includes displays for player card stats
    """
    http_method_names = ['get']

    def get(self, request, year, abbreviation):
        team = collect_team(year, abbreviation)
        team = collect_roster(team)
        team = collect_card_stats(team)
        config = RequestConfig(request)
        hitters_card = TeamHitter(team['card_stats']['hitters'], prefix='hit-')
        pitchers_card = TeamPitcher(team['card_stats']['pitchers'], prefix='pit-')
        config.configure(hitters_card)
        config.configure(pitchers_card)
        context = {
            'hitters_card': hitters_card,
            'pitchers_card': pitchers_card,
            'team': team,
        }
        return render(request, 'league/team/roster.html', context)


class TeamArbitration(View):

    def get(self, request, year, abbreviation):
        team = collect_team(year=year, abbreviation=abbreviation)
        team = collect_roster(team)
        team = collect_payroll(team)
        renewable = collect_renewable(team)
        guarenteed = collect_guarenteed(team)
        arbitration = collect_arbitration(team)
        renewable = RenewableList(request.POST or None, renewable=renewable)
        context = {
            'team': team,
            'renewable': renewable,
            'guarenteed': guarenteed,
            'arbitration': arbitration,
        }
        return render(request, 'league/team/arbitration.html', context)

django_strat/strat/league/templates/league/league/draft.html
{% extends 'homepage/base.html' %}
{% load humanize %}

{% block page_title%}
<title>Draft</title>
{% endblock%}

{% block content %}
<h2><a href="{% url 'league:draft_players_index' year %}">Players In Draft</a> </h2>
<h2><a href="{% url 'league:draft_picks_index' year %}">Draft Picks</a> </h2>
{% endblock %}

django_strat/strat/league/templates/league/league/draft_picks.html
{% extends 'homepage/base.html' %}
{% load humanize %}

{% block page_title%}
<title>{{year}} Draft Pick List</title>
{% endblock%}

{% block content %}
<h1>Draft Pick Listing</h1>
    {% for t in teams %}
        <h2>{{t.location}} {{t.nickname}}</h2>
        <ul>
            {% for d in draft_picks %}
                {% if d.pick.owner == t.franchise %}
                    <li>{{d.pick.original_team.location}}'s {{d.pick.round | ordinal}} round pick ({{d.number}})</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% endfor %}
{% endblock %}

django_strat/strat/league/templates/league/league/draft_players.html
{% extends 'homepage/base.html' %}
{% load humanize %}

{% block page_title%}
<title>{{year}} Draft List</title>
{% endblock%}

{% block content %}
<h1>Draft Pick Listing</h1>
        <table border="1">
            <tr>
                <th colspan="2">Player</th>
                <th>Contract</th>
                <th>Salary</th>
            </tr>
            {% for d in draft_players %}
                <tr>
                    <td>DRAFT</td>
                    <td><a href="{% url 'league:player_detail' d.player.id %}">
                        {{d.player.last_name}}, {{d.player.first_name}}</a> </td>
                    <td align="center">{{d.contract}}</td>
                    <td>${{d.salary|intcomma}}</td>
                </tr>
            {% endfor %}
        </table>
{% endblock %}

django_strat/strat/league/templates/league/league/free_agents.html
{% extends 'homepage/base.html' %}
{% load humanize %}

{% block page_title %}
<title>{{year}} Free Agents</title>
{% endblock %}


{% block content %}
<h1>Free Agent Listing</h1>
<table border="1">
    <tr>
        <th colspan="2">Player</th>
        <th>Auction Ends</th>
        <th>Length</th>
        <th>Salary</th>
        <th>Bid Value</th>
    </tr>
    {% for f in free_agents %}
    <tr>
        <td>BID</td>
        <td><a href="{% url 'league:player_detail' f.player.id %}">{{f.player.last_name}}, {{f.player.first_name}}</a> </td>
        {% if f.auction_ends %}
            <td>{{f.auction_ends}}</td>
        {% else %}
            <td></td>
        {% endif %}
        {% if f.bid_length %}
            <td>{{f.bid_length}}</td>
        {% else %}
            <td></td>
        {% endif %}
        {% if f.bid_salary %}
            <td>${{f.bid_salary|intcomma}}</td>
        {% else %}
            <td></td>
        {% endif %}
        {% if f.bid_value %}
            <td>${{f.bid_value|intcomma}}</td>
        {% else %}
            <td></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>
{% endblock %}

django_strat/strat/league/templates/league/league/trade_detail.html
{% extends 'homepage/base.html' %}
{% load humanize %}

{% block page_title %}
<title>BAD League Trade Detail</title>
{% endblock page_title %}

{% block content %}
<h1>
    Trade between
    {% for team in trade.trade.0.teams.all %}
        {{team.location}} {{team.nickname}}
        {% if forloop.revcounter0 >= 2 %}, {% endif %}
        {% if forloop.revcounter0 == 1 %}and{% endif %}
    {% endfor %}
</h1>
<h3>
    Trade occured {{trade.trade.0.date}}
</h3>
<ul>
    {% for tp in trade.trade_vector %}
    <h2>{{tp.giving.location}} is sending to {{tp.receiving.location}}:</h2>
    <ul>
        {% for p in tp.players %}
            <li>{{p.player}}</li>
        {% endfor %}
        {% for p in tp.picks %}
            <li>{{p.draft_pick}}</li>
        {% endfor %}
        {% for m in tp.money %}
            <li>${{m.money|intcomma}} for {{m.payroll_note}}'s {{m.year}} salary</li>
        {% endfor %}
    </ul>
    {% endfor %}
</ul>
{% endblock content %}

django_strat/strat/league/templates/league/league/trade_index.html
{% extends 'homepage/base.html' %}

{% block page_title %}
<title>BAD League-Trades</title>
{% endblock page_title %}

{% block content %}
<h1>Trades in {{year}}</h1>
    <ul>
        {% for t in trades %}
        <li>
            <a href="{% url 'league:trade_detail' t.trade.0.id %}">
                {{t.trade.0.date|date:'M jS'}} Trade between
                {% for tm in t.trade.0.teams.all %}
                    {{tm.location}}
                    {% if forloop.revcounter0 >= 2 %}, {% endif %}
                    {% if forloop.revcounter0 == 1 %}and{% endif %}
                {% endfor %}
            </a>
        </li>
        {% endfor %}
    </ul>
{% endblock content %}