django_strat/strat/league/urls.py
from django.urls import path

from .views import players, teams, league

app_name = 'league'
urlpatterns = [
    path('players/', players.IndexView.as_view(), name='player_index'),
    path('players/<str:player_id>/', players.PlayerDetail.as_view(), name='player_detail'),
    # path('players/<str:player_id>/contract', views.contract, name='player_contract'),
    path('teams/', teams.TeamIndex.as_view(), name='team_index'),
    path('teams/<int:year>', teams.TeamIndex.as_view(), name='team_index'),
    path('teams/<int:year>/<str:abbreviation>/', teams.TeamRoster.as_view(), name='team_roster'),
    path('teams/<int:year>/<str:abbreviation>/stats/', teams.TeamRoster.as_view(), name='team_stats'),
    path('teams/<int:year>/<str:abbreviation>/roster/', teams.TeamRoster.as_view(), name='team_roster'),
    path('teams/<int:year>/<str:abbreviation>/contracts/', teams.TeamContracts.as_view(), name='team_contracts'),
    path('teams/<int:year>/<str:abbreviation>/arbitration/', teams.TeamArbitration.as_view(),
         name='team_arbitration'),
    path('teams/<int:year>/<str:abbreviation>/draft_picks/',
         teams.TeamDraftPick.as_view(), name='team_draft_picks'),
    path('draft', league.LeagueDraft.as_view(), name='draft'),
    path('draft/<int:year>/picks_index', league.LeagueDraftPicks.as_view(), name='draft_picks_index'),
    path('draft/<int:year>/players_index', league.LeagueDraftPlayers.as_view(), name='draft_players_index'),
    path('trades', league.LeagueTradesIndex.as_view(), name='trades_index'),
    path('trades/<int:id>', league.TradeDetail.as_view(), name='trade_detail'),
    path('free_agents', league.LeagueFreeAgentIndex.as_view(), name='free_agent_index'),
    ]

django_strat/strat/strat/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('homepage.urls')),
    path('league/', include('league.urls')),
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('admin/', admin.site.urls),
]

django_strat/strat/league/models/teams.py
from django.contrib.auth import get_user_model
from django.db import models
User = get_user_model()


class Ballpark(models.Model):
    id = models.CharField(primary_key=True, max_length=10)
    name = models.CharField(max_length=75)
    location = models.CharField(max_length = 50)
    year = models.IntegerField()
    singles_left = models.IntegerField()
    singles_right = models.IntegerField()
    homeruns_left = models.IntegerField()
    homeruns_right = models.IntegerField()

    class Meta:
        ordering = ['-year', 'location']

    def __str__(self):
        return '{} {} Ballpark'.format(self.year, self.location)


class Franchise(models.Model):
    id = models.CharField(primary_key=True, max_length=20)
    owner = models.ForeignKey(User, db_column='current_owner', null=True, on_delete=models.SET_NULL)
    location = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)

    class Meta:
        ordering = ['location']

    def __str__(self):
        return '{} {} Franchise'.format(self.location, self.nickname)


class Team(models.Model):
    id = models.CharField(primary_key=True, max_length=20)
    year = models.IntegerField()
    abbreviation = models.CharField(max_length=5)
    franchise = models.ForeignKey(Franchise, db_column='franchise', on_delete=models.CASCADE)
    location = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    owner = models.ForeignKey(User, db_column='owner', null=True, on_delete=models.SET_NULL)
    # Setting up division choices
    ALW = 'ALW'
    ALE = 'ALE'
    NLW = 'NLW'
    NLE = 'NLE'
    division_choices = (
        (ALW, 'AL West'),
        (ALE, 'AL East'),
        (NLW, 'NL West'),
        (NLE, 'NL East'),
    )
    division = models.CharField(max_length=12, choices=division_choices)
    ballpark = models.ForeignKey(Ballpark, db_column='ballpark', on_delete=models.PROTECT)

    class Meta:
        ordering = ['-year', 'location']

    def __str__(self):
        return '{} {} {}'.format(self.year, self.location, self.nickname)


class Payroll(models.Model):
    receiving = models.ForeignKey(Franchise,
                                  db_column='receiving',
                                  null=True, blank=True,
                                  related_name='receiving',
                                  on_delete=models.SET_NULL)
    paying = models.ForeignKey(Franchise,
                               db_column='paying',
                               null=True, blank=True,
                               related_name='paying',
                               on_delete=models.SET_NULL)
    year = models.IntegerField()
    money = models.IntegerField()
    note = models.TextField()

    class Meta:
        ordering = ['year', 'note']

    def __str__(self):
        return '<Payroll Adjustment: {} {}>'.format(self.year, self.note)

django_strat/strat/league/forms/teams.py
from django import forms

renewable_choices = (
    ('keep', 'Keep'),
    ('ltc', 'Long Term Contract'),
    ('rel', 'Release'),
)

guarenteed_choices = (
    ('keep', 'Keep'),
    ('rel', 'Release'),
)


class Renewable(forms.Form):

    def __init__(self, *args, **kwargs):
        player = kwargs.pop('player')
        super(RenewableContract, self).__init__(*args, **kwargs)

        # self.fields['name'] = forms.Field(widget=forms.HiddenInput,
        #                                   label='{}, {}'.format(player['contract'].player.last_name,
        #                                                         player['contract'].player.first_name))
        # self.fields['salary'] = forms.Field(widget=forms.HiddenInput,
        #                                     label='{}'.format(player['contract'].salary))
        # self.fields['contract'] = forms.Field(widget=forms.HiddenInput,
        #                                       label='{}'.format(player['contract'].type))
        self.fields['{}'.format(player['id'])] = \
            forms.MultipleChoiceField(choices=renewable_choices,
                                      widget=forms.RadioSelect,
                                      label='{}, {}'.format(player['contract'].player.last_name,
                                                            player['contract'].player.first_name,))


class RenewableList(forms.Form):

    def __init__(self, *args, **kwargs):
        renewable = kwargs.pop('renewable')
        super(RenewableList, self).__init__(*args, **kwargs)

        for i, player in enumerate(renewable):
            self.fields['name_{}'.format(player['id'])] = \
                forms.Field(widget=forms.HiddenInput,
                            label='{}, {}'.format(player['player'].last_name,
                                                  player['player'].first_name),
                            show_hidden_initial=True)
            self.fields['salary_{}'.format(player['id'])] = \
                forms.Field(widget=forms.HiddenInput,
                            label='{}'.format(player['contract'].salary),
                            show_hidden_initial=True)
            self.fields['contract_{}'.format(player['id'])] = \
                forms.Field(widget=forms.HiddenInput,
                            label='{}'.format(player['contract'].type))
            self.fields['choice_{}'.format(player['id'])] = \
                forms.MultipleChoiceField(choices=renewable_choices,
                                          widget=forms.RadioSelect,
                                          label='{}'.format(player['id']))

django_strat/strat/league/views/home.py
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'league/home_page.html'

    def get_queryset(self):
        """
        Gives an empty queryset to allow loading of the home page.
        """
        return None

django_strat/strat/league/views/league.py
from django.shortcuts import render, get_list_or_404
from django.utils import timezone
from django.views import View

from league.models.teams import Team
from league.models.transactions import DraftPick, AvailableFreeAgent, AvailableDraftPick
from .league_helper import collect_trades, collect_trade


class LeagueDraft(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year
        context = {
            'year': year,
        }
        return render(request, 'league/league/draft.html', context)


class LeagueDraftPicks(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        teams = get_list_or_404(Team.objects.filter(year=year))
        picks = get_list_or_404(DraftPick.objects.filter(year=year)
                                      .order_by('round', 'order'))
        draft_picks = []
        for p in picks:
            number = ((p.round - 1) * 16) + p.order
            dft_pick = {
                'pick': p,
                'number': number,
            }
            draft_picks.append(dft_pick)
        context = {
            'teams': teams,
            'draft_picks': draft_picks
        }
        return render(request, 'league/league/draft_picks.html', context)


class LeagueDraftPlayers(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        draft_players = AvailableDraftPick.objects.filter(year=year)

        context = {
            'year': year,
            'draft_players': draft_players,
        }
        return render(request, 'league/league/draft_players.html', context)


class LeagueTradesIndex(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        trades = collect_trades(year)
        context = {
            'trades': trades,
            'year': year,
        }
        return render(request, 'league/league/trade_index.html', context)


class TradeDetail(View):

    def get(self, request, id):
        trade = collect_trade(id)
        context = {
            'trade': trade
        }
        return render(request, 'league/league/trade_detail.html', context)

class LeagueFreeAgentIndex(View):

    def get(self, request, year=None):
        if year is None:
            year = timezone.now().year

        free_agents = AvailableFreeAgent.objects.filter(year=year)
        context = {
            'free_agents': free_agents,
            'year': year,
        }
        return render(request, 'league/league/free_agents.html', context)

django_strat/strat/league/views/league_helper.py
from league.models.transactions import Trades, TradePart,\
    TradePlayer, TradePick, TradeMoney


def collect_trades(year, team=None):
    if team is None:
        trade = Trades.objects.filter(year=year).order_by('date')
    else:
        trade = Trades.objects.filter(year=year, team=team).order_by('date')
    trades = []
    for t in trade:
        trd = collect_trade(t.id)
        trades.append(trd)
    return trades


def collect_trade(id):
    trade = Trades.objects.filter(id=id)
    trade_part = TradePart.objects.filter(trade=id)
    trade_vector_part = collect_trade_vectors(trade_part)
    trade_vector = []
    for t in trade_vector_part:
        trade_vector.append(collect_vector_part(t['giving'], t['receiving'], id))
    trade = {
        'trade': trade,
        'trade_vector': trade_vector,
    }
    return trade


def collect_trade_vectors(trade_parts):
    all_trade_vectors = []
    unique_trade_vectors = []
    for t in trade_parts:
        v = {
            'giving': t.team_giving,
            'receiving': t.team_receiving,
        }
        all_trade_vectors.append(v)
    for v in all_trade_vectors:
        if v not in unique_trade_vectors:
            unique_trade_vectors.append(v)
    return unique_trade_vectors


def collect_vector_part(giving, receiving, id):
    players = TradePlayer.objects.filter(team_giving=giving, team_receiving=receiving, trade=id)
    picks = TradePick.objects.filter(team_giving=giving, team_receiving=receiving, trade=id)
    money = TradeMoney.objects.filter(team_giving=giving, team_receiving=receiving, trade=id)
    vector = {
        'giving': giving,
        'receiving': receiving,
        'players': players,
        'picks': picks,
        'money': money,
    }
    return vector

django_strat/strat/league/views/player_helper.py
from league.models.transactions import AvailableFreeAgent, AvailableDraftPick
from league.models.players import HitterCardStats, \
    Contract
from league.models.players import HitterCardStats, \
    Contract
from league.models.transactions import AvailableFreeAgent, AvailableDraftPick


def collect_team(player, year):
    team = ''
    contract = Contract.objects.filter(player=player, year=year)
    if len(contract) == 1:
        team = '{} {}'.format(contract[0].team.location, contract[0].team.nickname)
    elif len(contract) == 0:
        free_agents = AvailableFreeAgent.objects.filter(player=player, year=year)
        if len(free_agents) == 1:
            team = 'Free Agent'
        else:
            draft_picks = AvailableDraftPick.objects.filter(player=player, year=year)
            if len(draft_picks) == 1:
                team = 'Available in Draft'
    return team


def collect_player_position(player):
    position = ''
    if player.player_type == 'p':
        position += 'Pitcher, '
    if player.player_type == 'x':
        position += 'Pitcher, '
    if player.player_type in 'hx':
        cards = HitterCardStats.objects.filter(player=player)
        defensive_strings = ''
        for c in cards:
            defensive_strings += '{} '.format(c.defensive_string)
        while len(defensive_strings) > 3:
            if defensive_strings[:2] == 'c-':
                if 'Catcher' not in position:
                    position += 'Catcher, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == '1b-':
                if 'Firstbase' not in position:
                    position += 'Firstbase, '
                defensive_strings = defensive_strings[3:]
            elif defensive_strings[:3] == '2b-':
                if 'Secondbase' not in position:
                    position += 'Secondbase, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == '3b-':
                if 'Thirdbase' not in position:
                    position += 'Thirdbase, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'ss-':
                if 'Shortstop' not in position:
                    position += 'Shortstop, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'lf-':
                if 'Left Field' not in position:
                    position += 'Left Field, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'cf-':
                if 'Center Field' not in position:
                    position += 'Center Field, '
                defensive_strings = defensive_strings[2:]
            elif defensive_strings[:3] == 'rf-':
                if 'Right Field' not in position:
                    position += 'Right Field, '
            else:
                defensive_strings = defensive_strings[1:]
    position = position[:-2]
    return position

django_strat/strat/league/views/players.py
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from django.views import generic, View

from league.models.players import Player, HitterCardStats, PitcherCardStats
from .player_helper import collect_player_position, collect_team


class IndexView(generic.ListView):
    template_name = 'league/player/index.html'
    context_object_name = 'player_list'

    def get_queryset(self):
        return Player.objects.filter(active=True)


class PlayerDetail(View):

    def get(self, request, player_id):
        player = get_object_or_404(Player, pk=player_id)
        hitting_card_stats = HitterCardStats.objects.filter(player=player_id).order_by('year')
        pitching_card_stats = PitcherCardStats.objects.filter(player=player_id).order_by('year')
        positions = collect_player_position(player)
        year = timezone.now().year
        teams = collect_team(player, year)
        context = {
            'player': player,
            'bats': player.batting_hand(),
            'throws': player.throwing_hand(),
            'positions': positions,
            'teams': teams,
            'hitting_card_stats': hitting_card_stats,
            'pitching_card_stats': pitching_card_stats,
        }
        return render(request, 'league/player/detail.html', context)

django_strat/strat/league/templates/league/team/arbitration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action=".">
    <input type=submit>
    <h2>Renewable Contracts</h2>
    <table>
        {% csrf_token %}
        {{ renewable.as_table }}
</form>
</table>
<h2>Guarenteed Contracts</h2>
<table>
    <form>
        {{guarenteed.as_table}}
    </form>
</table>
</body>
</html>

django_strat/strat/league/templates/league/team/base.html
{% extends 'homepage/base.html' %}
{% load static %}

{% block page_title%}
    <title>{{team.year}} {{team.location}} {{team.nickname}}</title>
{% endblock page_title %}

{% block part_header %}
    {% include 'league/team/header.html' %}
{% endblock part_header %}

{% block part_navigation %}
    <h2><a href="{% url 'league:team_roster' team.team.year team.team.abbreviation %}">Roster</a> |
        <a href="{% url 'league:team_stats' team.team.year team.team.abbreviation %}">Statistics</a> |
        <a href="{% url 'league:team_contracts' team.team.year team.team.abbreviation %}">Contracts</a> |
        <a href="{% url 'league:team_arbitration' team.team.year team.team.abbreviation %}">Arbitration</a> |
        Draft Results |
        <a href="{% url 'league:team_draft_picks' team.team.year team.team.abbreviation %}">Draft Picks</a>
    </h2>
{% endblock part_navigation %}

django_strat/strat/league/templates/league/team/contracts.html
{% extends "./base.html" %}

{% load humanize %}
{% block content %}
<style>
    td.renewable {
        text-align: Center;
    }
    td.free_agent {
        text-align: Center;
        background-color: LightPink;
        color: DarkRed;
    }
    td.guarenteed {
        text-align: Right;
    }
    td.negative {
        color: Red;
        text-align: Right;
    }
    td.positive {
        text-align: Right;
    }
</style>
<table>
    <tr>
        <th>Player</th>
        <th>Contract</th>
        <th>{{team.team.year}}</th>
        <th>{{team.team.year|add:"+1"}}</th>
        <th>{{team.team.year|add:"+2"}}</th>
        <th>{{team.team.year|add:"+3"}}</th>
        <th>{{team.team.year|add:"+4"}}</th>
    </tr>
    {% for p in team.roster %}
    <tr>
        <td><a href="{% url 'league:player_detail' p.contract.contract.player_id %}">
            {{p.contract.contract.player.last_name}},
            {{p.contract.contract.player.first_name}}</a></td>
        <td align="center">{{p.contract.display}}</td>
        <td align="right">${{p.contract.year_display.0| intcomma}}</td>
        
        {% if p.contract.year_display.1 == 'FA' %}
        <td class="free_agent"><strong>{{p.contract.year_display.1}}</strong></td>
        {% elif p.contract.year_display.1 in contract_list %}
            <td class="renewable">{{p.contract.year_display.1}}</td>
        {% elif p.contract.year_display.1 == '' %}
            <td></td>
        {% else %}
            <td class="guarenteed">${{p.contract.year_display.1| intcomma}}</td>
        {% endif %}
        
        {% if p.contract.year_display.2 == 'FA' %}
        <td class="free_agent"><strong>{{p.contract.year_display.2}}</strong></td>
        {% elif p.contract.year_display.2 in contract_list %}
            <td class="renewable">{{p.contract.year_display.2}}</td>
        {% elif p.contract.year_display.2 == '' %}
            <td></td>
        {% else %}
            <td class="guarenteed">${{p.contract.year_display.2| intcomma}}</td>
        {% endif %}
        
        {% if p.contract.year_display.3 == 'FA' %}
        <td class="free_agent"><strong>{{p.contract.year_display.3}}</strong></td>
        {% elif p.contract.year_display.3 in contract_list %}
            <td class="renewable">{{p.contract.year_display.3}}</td>
        {% elif p.contract.year_display.3 == '' %}
            <td></td>
        {% else %}
            <td class="guarenteed">${{p.contract.year_display.3| intcomma}}</td>
        {% endif %}
        
        {% if p.contract.year_display.4 == 'FA' %}
        <td class="free_agent"><strong>{{p.contract.year_display.4}}</strong></td>
        {% elif p.contract.year_display.4 in contract_list %}
            <td class="renewable">{{p.contract.year_display.4}}</td>
        {% elif p.contract.year_display.4 == '' %}
            <td></td>
        {% else %}
            <td class="guarenteed">${{p.contract.year_display.4| intcomma}}</td>
        {% endif %}
    </tr>
    {% endfor %}
    <tr>
        <td colspan="2"><strong>Total Payroll</strong></td>
        {% for i in team.payroll.gross_payroll %}
            <td align="right"><strong>${{i|intcomma}}</strong></td>
        {% endfor %}
    </tr>
    {% for a in team.adjustment %}
    <tr>
        <td colspan="2">{{a.note}}</td>
        {% for i in a.money %}
            {% if i %}
                {% if i > 0 %}
                    <td class="positive">${{i|intcomma}}</td>
                {% else %}
                    <td class="negative">-${{i|intcomma|slice:"1:"}}</td>
                {% endif %}
            {% else %}
                <td></td>
            {% endif %}
        {% endfor %}
    </tr>
    {% endfor %}
    <tr>
        <td colspan="2"><strong>Total Adjustments</strong></td>
        {% for i in team.payroll.payroll_adjustments %}
            <td align="right"><strong>${{i|intcomma}}</strong></td>
        {% endfor %}
    </tr>
    <tr>
        <td colspan="2"><strong>Payroll + Adjustments</strong></td>
        {% for i in team.payroll.net_payroll %}
            <td align="right"><strong>${{i|intcomma}}</strong></td>
        {% endfor %}
    </tr>
    <tr>
        <td colspan="2"><strong>Salary Cap</strong></td>
        {% for i in team.payroll.salary_cap %}
            <td align="right"><strong>${{i|intcomma}}</strong></td>
        {% endfor %}
    </tr>
    <tr>
        <td colspan="2"><strong>Total Remaining</strong></td>
        {% for i in team.payroll.payroll_remaining %}
            <td align="right"><strong>${{i|intcomma}}</strong></td>
        {% endfor %}
    </tr>
</table>
{% endblock %}

django_strat/strat/league/templates/league/team/detail.html
{% extends "./base.html" %}

{% block page_title %}
    <title>{{team.year}} {{team.location}} {{team.nickname}}</title>
{% endblock page_title %}

{% block content %}
    {% for player in roster %}
        <h3>{{player}}</h3>
    {% endfor %}
{% endblock content %}

django_strat/strat/league/templates/league/team/index.html
{% extends 'homepage/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
    {% if last_year in year_list %}
        <h2><a href="{% url 'league:team_index' last_year %}">Previous Year</a> </h2>
    {% endif %}
    <h1>{{year}} BAD League Teams</h1>
    {% if next_year in year_list %}
        <h2><a href="{% url 'league:team_index' next_year %}">Next Year</a> </h2>
    {% endif %}
    <table border="1">
        <tr>
            <th colspan="2">Team</th>
            <th>Owner</th>
            <th>Ballpark</th>
            <th>Division</th>
            <th>Players</th>
            <th>Payroll Remaining</th>
        </tr>
        {% for t in team_list %}
            <tr>
                <td><img src="{% static "league/" %}{{year}}{{t.team.abbreviation}}.jpg"
                    alt="{{t.team.location}} {{t.team.nickname}} Logo"/> </td>
                <td><a href="{% url 'league:team_roster' year t.team.abbreviation %}">{{t.team.location}} {{t.team.nickname}}</a></td>
                {% if user %}
                    <td><a href="mailto:{{team.owner.email}}">{{t.team.owner.first_name}} {{t.team.owner.last_name}}</a> </td>
                {% else %}
                    <td>{{t.team.owner.first_name}} {{t.team.owner.last_name}}</td>
                {% endif %}
                <td>{{t.team.ballpark.year}} {{t.team.ballpark.location}}</td>
                <td>{{t.team.get_division_display}}</td>
                <td align="right">45 Man: {{t.payroll.45_man}}<br>40 Man: {{t.payroll.40_man}}</td>
                <td align="right">${{t.payroll.payroll_remaining.0|intcomma}}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

django_strat/strat/league/templates/league/team/off_season_contracts.html
{% extends "./base.html" %}

{% load humanize %}
{% load players_tags %}
{% block content %}
<h2>Players Currently Under Contract for {{header.team.year}}</h2>
<h3>Total Players on 45 man roster: {{contracts.players_signed}} ({{contracts.open_roster_slots}} spots open)</h3>
<h3>Total Players on 40 man roster: {{contracts.cards_signed}} ({{contracts.open_carded_slots}} spots open)</h3>
<h3>Total Salary Cap space remaining: ${{payroll.net_remaining.0|intcomma}}</h3>
<h3>Renewable Contracts</h3>
<table>
    <form>
    <tr>
        <th>Player</th>
        <th>Contract</th>
        <th>Salary</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
{% for c in contracts.early_contracts %}
    <tr>
        <td><a href="{% url 'league:player_detail' c.player.id %}">
            {{c.player.last_name}}, {{c.player.first_name}}</a> </td>
        <td align="center">{{c.type}}</td>
        <td align="right">${{c.salary|intcomma}}</td>
        {% if is_owner %}
            <td><input type="radio" value="keep" name="{{c.player.id}}" checked="checked">Keep</td>
            <td><input type="radio" value="long_term" name="{{c.player.id}}">Long Term Deal</td>
            <td><input type="radio" value="non-tender" name="{{c.player.id}}">Non-Tender</td>
        {% endif %}
     </tr>
{% endfor %}
    <tr>
        <td colspan="6">Non-Tendered Players go into the draft.</td>
    </tr>
</table>
<h3>Arbitration Eligible Players</h3>
{% if contracts.arbitration_info %}
<table>
    <tr>
        <th>Player</th>
        <th>Contract</th>
        <th>Minimum Salary</th>
        <th>Median Salary</th>
        <th>Maximum Salary</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
{% for c in contracts.arbitration_info %}
    <tr>
        <td><a href="{% url 'league:player_detail' c.player.id %}">
            {{c.player.last_name}}, {{c.player.first_name}}</a> </td>
        <td align="center">{{c.type}}</td>
        <td align="right">${{c.minimum_contract|intcomma}}</td>
        <td align="right">${{c.median_contract|intcomma}}</td>
        <td align="right">${{c.maximum_contract|intcomma}}</td>
        {% if is_owner %}
            <td><input type="radio" value="arbitration" name="{{c.player.id}}" checked="checked">Go To Arbitration</td>
            <td><input type="radio" value="long_term" name="{{c.player.id}}">Long Term Deal</td>
            <td><input type="radio" value="non_tender" name="{{c.player.id}}">Non-Tender</td>
        {% endif %}
    </tr>
{% endfor %}
    <tr>
        <td colspan="8">Non-Tendered Players become free agents.</td>
    </tr>
</table>
{% else %}
<h3>No Arbitration Eligible Players</h3>
{% endif %}
<h3>Guarenteed Contracts</h3>
<table>
    <tr>
        <th>Player</th>
        <th>Contract</th>
        <th>Salary</th>
        <th></th>
        <th></th>
    </tr>
{% for c in contracts.guarenteed_contracts %}
    <tr>
        <td><a href="{% url 'league:player_detail' c.player.id %}">
            {{c.player.last_name}}, {{c.player.first_name}}</a> </td>
        <td align="center">{{c.contract_season}}-{{c.length}}, {{c.type}}</td>
        <td align="right">${{c.salary|intcomma}}</td>
        {% if is_owner %}
            <td><input type="radio" value="keep" name="{{c.player.id}}" checked="checked">Keep</td>
            <td><input type="radio" value="release" name="{{c.player.id}}">Release</td>
        {% endif %}
    </tr>
{% endfor %}
</table>
<p>Released players must be paid for in full, and become free agents if not signed during their waiver period.</p>
    {% if is_owner %}
        <input type="submit" value="Approve">
        <input type="button" value="Cancel">
    {% endif %}
    </form>
{% endblock %}

django_strat/strat/league/templates/league/team/roster.html
{% extends "./base.html" %}
{% load render_table from django_tables2 %}

{% load humanize %}

{% block content %}
    <h2>Hitters Card Stats</h2>
    {% render_table hitters_card %}
    <h2>Pitchers Card Stats</h2>
    {% render_table pitchers_card %}
    <h2>Uncarded Players</h2>
    <ul>
        {% for p in team.card_stats.uncarded %}
        <li><a href="{% url 'league:player_detail' p.id %}">{{p}}</a> </li>
        {% endfor %}
    </ul>
{% endblock %}